vpc_name:
  - homelab-vpc01
  - homelab-vpc02

subnets:
  - name: subnet01
    cidr: 10.0.0.0/24
    region: asia-south2
    network:
      name:
        selfLink: "https://www.googleapis.com/compute/v1/projects/cogent-tide-366115/global/networks/homelab-vpc01"
      
  - name: subnet02
    cidr: 10.2.0.0/24
    region: europe-west4
    network:
      name:
        selfLink: "https://www.googleapis.com/compute/v1/projects/cogent-tide-366115/global/networks/homelab-vpc02"
      