- name: Install pre-requisites  packages for apt module
  hosts: homelab
  become: yes
  vars:
    ansible_become_password: "{{ lookup('env', 'BECOME_PASS') }}"
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        state: present 
        pkg:
        - python3-google-auth
        - python3-requests