name: Cloud SQL Creation

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - 'group_vars/cloudsql/vars.yaml'

env:
  SERVICE_ACCOUNT: ${{ secrets.GCP_SA_TOKEN }}
      
jobs:
  cloudsql:
    runs-on: ansible-gcp-ninja

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Cloud SQL Creation Playbook
      run: |
        ansible-playbook playbooks/cloudsql/cloudsql.yaml -i inventory/homelab