name: Compute Disk creation

on:
  workflow_dispatch:

  pull_request:
    branches:
      - 'main'
    paths:
      - 'playbooks/compute-disk/disks.yaml'

env:
  SERVICE_ACCOUNT: ${{ secrets.GCP_SA_TOKEN }}
      
jobs:
  disks:
    runs-on: ansible-gcp-ninja

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run VPC Creation Playbook
      run: |
        ansible-playbook playbooks/compute-disk/disks.yaml -i inventory/homelab